---
deployment:
 tasks:
 - export DEPLOYPATH=/home/rgzvbrx2j6qv/drchadhadentalclinic.com
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp style.css $DEPLOYPATH
 - /bin/cp -R images $DEPLOYPATH
 - /bin/cp -R css $DEPLOYPATH
 - /bin/cp -R fonts $DEPLOYPATH
 - /bin/cp -R js $DEPLOYPATH
 - /bin/cp -R scss $DEPLOYPATH
 - /bin/cp -R css $DEPLOYPATH
 - /bin/cp about.html $DEPLOYPATH
 - /bin/cp contact.html $DEPLOYPATH
 - /bin/cp services.html $DEPLOYPATH
 - /bin/cp prepros-6.config $DEPLOYPATH
